// Mocks generated by Mockito 5.4.6 from annotations
// in so_bicos/test/ui/auth/login/viewmodels/login_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result_dart/result_dart.dart' as _i4;
import 'package:so_bicos/core/data/repositories/auth/auth_repository.dart'
    as _i2;
import 'package:so_bicos/core/domain/models/auth/user.dart' as _i5;
import 'package:so_bicos/ui/designsystem/localization/app_localizations.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class AuthRepositoryMock extends _i1.Mock implements _i2.AuthRepository {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<_i4.ResultDart<_i5.User, Exception>> createUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [email, password]),
            returnValue: _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                this,
                Invocation.method(#createUser, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                    this,
                    Invocation.method(#createUser, [email, password]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i5.User, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i5.User, Exception>> loginEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginEmail, [email, password]),
            returnValue: _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                this,
                Invocation.method(#loginEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                    this,
                    Invocation.method(#loginEmail, [email, password]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i5.User, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i5.User, Exception>> loginPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#loginPhone, [phone]),
            returnValue: _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                this,
                Invocation.method(#loginPhone, [phone]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                    this,
                    Invocation.method(#loginPhone, [phone]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i5.User, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i5.User, Exception>> verifyPhoneCode(
    String? verificationId,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneCode, [verificationId, code]),
            returnValue: _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                this,
                Invocation.method(#verifyPhoneCode, [verificationId, code]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                    this,
                    Invocation.method(#verifyPhoneCode, [verificationId, code]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i5.User, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<_i5.User, Exception>> getLoggedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUser, []),
            returnValue: _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                this,
                Invocation.method(#getLoggedUser, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<_i5.User, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<_i5.User, Exception>>(
                    this,
                    Invocation.method(#getLoggedUser, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i5.User, Exception>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class AppLocalizationsMock extends _i1.Mock implements _i8.AppLocalizations {
  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  String get signup =>
      (super.noSuchMethod(
            Invocation.getter(#signup),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#signup),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#signup),
            ),
          )
          as String);

  @override
  String get welcome =>
      (super.noSuchMethod(
            Invocation.getter(#welcome),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#welcome),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#welcome),
            ),
          )
          as String);

  @override
  String get dont_have_an_account =>
      (super.noSuchMethod(
            Invocation.getter(#dont_have_an_account),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dont_have_an_account),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dont_have_an_account),
            ),
          )
          as String);

  @override
  String get create_an_account =>
      (super.noSuchMethod(
            Invocation.getter(#create_an_account),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#create_an_account),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#create_an_account),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get repeat_password =>
      (super.noSuchMethod(
            Invocation.getter(#repeat_password),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#repeat_password),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#repeat_password),
            ),
          )
          as String);

  @override
  String get this_field_cant_be_empty_or_blank =>
      (super.noSuchMethod(
            Invocation.getter(#this_field_cant_be_empty_or_blank),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#this_field_cant_be_empty_or_blank),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#this_field_cant_be_empty_or_blank),
            ),
          )
          as String);

  @override
  String get this_field_requires_a_valid_email =>
      (super.noSuchMethod(
            Invocation.getter(#this_field_requires_a_valid_email),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#this_field_requires_a_valid_email),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#this_field_requires_a_valid_email),
            ),
          )
          as String);

  @override
  String get password_mus_be_at_least_characters =>
      (super.noSuchMethod(
            Invocation.getter(#password_mus_be_at_least_characters),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#password_mus_be_at_least_characters),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#password_mus_be_at_least_characters),
            ),
          )
          as String);

  @override
  String get passwords_dont_match =>
      (super.noSuchMethod(
            Invocation.getter(#passwords_dont_match),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwords_dont_match),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwords_dont_match),
            ),
          )
          as String);

  @override
  String get logout =>
      (super.noSuchMethod(
            Invocation.getter(#logout),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#logout),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#logout),
            ),
          )
          as String);

  @override
  String get search =>
      (super.noSuchMethod(
            Invocation.getter(#search),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#search),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#search),
            ),
          )
          as String);
}
